name: Update Rain Heatmap

on:
  schedule:
    # Berjalan otomatis setiap 2 jam
    - cron: '0 */2 * * *'
  workflow_dispatch: # Tombol manual untuk tes langsung di web GitHub

jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: |
          python generate_map.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "DimasAdiNugroho-dryTundra"
          git config --global user.email "dimasadi030512@gmail.com"
          git add index.html cities.json
          git commit -m "chore: update daily rain heatmap [skip ci]"
          git push
